import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectWriter;
import com.nexmo.client.NexmoClient;
import com.nexmo.client.auth.TokenAuthMethod;
import com.nexmo.client.insight.InsightClient;
import com.nexmo.client.insight.advanced.AdvancedInsightResponse;

import org.apache.http.entity.ContentType;

import io.github.cdimascio.dotenv.Dotenv;
import spark.Route;
import spark.Spark;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final String NUMBER_PARAM = ":number";

    private static final String KEY = Dotenv.load().get("NEXMO_API_KEY");
    private static final String SECRET = Dotenv.load().get("NEXMO_API_SECRET");

    private static final int PORT = 3000;
    private static final String REQUEST_ROUTE = "api/" + NUMBER_PARAM;

    private final InsightClient insightClient = new NexmoClient(new TokenAuthMethod(KEY, SECRET)).getInsightClient();
    private final ObjectWriter writer = new ObjectMapper().writer();

    public static void main(String[] args) {
        new App().start();
    }

    /**
     * Start the Sparkframework Application
     */
    private void start() {
        Spark.port(PORT);
        Spark.get(REQUEST_ROUTE, createRequestRoute());
    }

    /**
     * @return A {@link Route} which will handle looking up the number insight
     *         information.
     */
    private Route createRequestRoute() {
        return (request, response) -> {
            final String number = request.params(NUMBER_PARAM);
            final AdvancedInsightResponse advancedInsightResponse = insightClient.getAdvancedNumberInsight(number, "",
                    "", true);

            response.type(ContentType.APPLICATION_JSON.getMimeType());
            return this.writer.writeValueAsString(advancedInsightResponse);
        };
    }
}
